# An√°lisis descriptivo de los datos

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/shopping_behavior_updated.csv')

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
columnas = df.columns
print("Columnas del DataFrame:")
print(columnas)

Columnas del DataFrame:
Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [ ]:
columnas_a_eliminar = ['Color','Customer ID', 'Purchase Amount (USD)', 'Season', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases', 'Location']
df = df.drop(columns=columnas_a_eliminar)
print(df)

      Age  Gender Item Purchased     Category Size  Review Rating
0      55    Male         Blouse     Clothing    L            3.1
1      19    Male        Sweater     Clothing    L            3.1
2      50    Male          Jeans     Clothing    S            3.1
3      21    Male        Sandals     Footwear    M            3.5
4      45    Male         Blouse     Clothing    M            2.7
...   ...     ...            ...          ...  ...            ...
3895   40  Female         Hoodie     Clothing    L            4.2
3896   52  Female       Backpack  Accessories    L            4.5
3897   46  Female           Belt  Accessories    L            2.9
3898   44  Female          Shoes     Footwear    S            3.8
3899   52  Female        Handbag  Accessories    M            3.1

[3900 rows x 6 columns]

In [ ]:
df = pd.get_dummies(df, columns=['Size', 'Category'])

In [ ]:
df['Age'] = df['Age']>df['Age'].median()
df['Review Rating'] = df['Review Rating']>df['Review Rating'].median()
df.rename(columns={'Gender': 'Femenino'}, inplace=True)
df['Femenino'] = df['Femenino'].replace({'Female': 1, 'Male': 0})
df.drop('Category_Accessories', axis=1, inplace=True)
df

,Age,Femenino,Item Purchased,Review Rating,Size_L,Size_M,Size_S,Size_XL,Category_Clothing,Category_Footwear,Category_Outerwear
0,True,0,Blouse,False,1,0,0,0,1,0,0
1,False,0,Sweater,False,1,0,0,0,1,0,0
2,True,0,Jeans,False,0,0,1,0,1,0,0
3,False,0,Sandals,False,0,1,0,0,0,1,0
4,True,0,Blouse,False,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3895,False,1,Hoodie,True,1,0,0,0,1,0,0
3896,True,1,Backpack,True,1,0,0,0,0,0,0
3897,True,1,Belt,False,1,0,0,0,0,0,0
3898,False,1,Shoes,True,0,0,1,0,0,1,0
3899,True,1,Handbag,False,0,1,0,0,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 3900 non-null   bool
 1   Femenino            3900 non-null   int64
 2   Item Purchased      3900 non-null   object
 3   Review Rating       3900 non-null   bool
 4   Size_L              3900 non-null   uint8
 5   Size_M              3900 non-null   uint8
 6   Size_S              3900 non-null   uint8
 7   Size_XL             3900 non-null   uint8
 8   Category_Clothing   3900 non-null   uint8
 9   Category_Footwear   3900 non-null   uint8
 10  Category_Outerwear  3900 non-null   uint8
dtypes: bool(2), int64(1), object(1), uint8(7)
memory usage: 95.3+ KB

In [ ]:
print(df.isnull().sum())

Age                   0
Femenino              0
Item Purchased        0
Review Rating         0
Size_L                0
Size_M                0
Size_S                0
Size_XL               0
Category_Clothing     0
Category_Footwear     0
Category_Outerwear    0
dtype: int64

In [ ]:
df['Item Purchased'].value_counts()

Blouse        171
Jewelry       171
Pants         171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Belt          161
Sunglasses    161
Coat          161
Sandals       160
Socks         159
Skirt         158
Shorts        157
Scarf         157
Hat           154
Handbag       153
Hoodie        151
Shoes         150
T-shirt       147
Sneakers      145
Boots         144
Backpack      143
Gloves        140
Jeans         124
Name: Item Purchased, dtype: int64

In [ ]:
df = df[~df['Item Purchased'].str.contains('Jewelry') & ~df['Item Purchased'].str.contains('Shirt')& ~df['Item Purchased'].str.contains('Blouse')
& ~df['Item Purchased'].str.contains('Sweater')& ~df['Item Purchased'].str.contains('Socks')& ~df['Item Purchased'].str.contains('Sandals')
& ~df['Item Purchased'].str.contains('Sunglasses')& ~df['Item Purchased'].str.contains('Coat')& ~df['Item Purchased'].str.contains('Jacket')
& ~df['Item Purchased'].str.contains('Skirt')& ~df['Item Purchased'].str.contains('Shorts')& ~df['Item Purchased'].str.contains('Scarf')
& ~df['Item Purchased'].str.contains('Handbag')& ~df['Item Purchased'].str.contains('Hoodie')
& ~df['Item Purchased'].str.contains('Shoes')& ~df['Item Purchased'].str.contains('T-shirt')
& ~df['Item Purchased'].str.contains('Backpack')& ~df['Item Purchased'].str.contains('Gloves')& ~df['Item Purchased'].str.contains('Jeans')
& ~df['Item Purchased'].str.contains('Hat')]

In [ ]:
df['Item Purchased'].value_counts()

Pants       171
Dress       166
Belt        161
Sneakers    145
Boots       144
Name: Item Purchased, dtype: int64

In [ ]:
mapeo_itempur = {'Pants': 1, 'Dress': 2, 'Belt': 3, 'Sneakers':4, 'Boots':5}

# Aplicar el reemplazo en la columna "Category"
df['Item Purchased'] = df['Item Purchased'].replace(mapeo_itempur)

<ipython-input-246-30fc79d3ba10>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Item Purchased'] = df['Item Purchased'].replace(mapeo_itempur)

In [ ]:
df.shape

(787, 11)

#Implementaci√≥n del modelo Random Forest

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X = df.drop('Item Purchased', axis=1)
y = df['Item Purchased']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar el modelo de Random Forest
rf=RandomForestClassifier(criterion="gini",n_estimators=10,min_samples_split=4, min_samples_leaf=2)

# Entrenar el modelo
rf.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = rf.predict(X_test)

# Evaluar el rendimiento del modelo
accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Classification Report:\n{classification_report_result}')

Accuracy: 0.6392405063291139
Classification Report:
              precision    recall  f1-score   support

           1       0.51      0.61      0.55        38
           2       0.38      0.29      0.33        31
           3       1.00      1.00      1.00        37
           4       0.57      0.57      0.57        23
           5       0.66      0.66      0.66        29

    accuracy                           0.64       158
   macro avg       0.62      0.62      0.62       158
weighted avg       0.63      0.64      0.63       158

In [ ]:
pred1=rf.predict(X_test)
print(X_test[:5],pred1[:5], y_test[:5])

        Age  Femenino  Review Rating  Size_L  Size_M  Size_S  Size_XL  \
2642  False         0           True       1       0       0        0
200   False         0          False       0       0       1        0
1006  False         0           True       0       0       1        0
958    True         0           True       0       0       0        1
1148  False         0          False       0       1       0        0

      Category_Clothing  Category_Footwear  Category_Outerwear
2642                  0                  0                   0
200                   1                  0                   0
1006                  1                  0                   0
958                   0                  1                   0
1148                  1                  0                   0   [3 1 1 4 1] 2642    3
200     2
1006    1
958     4
1148    1
Name: Item Purchased, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix
confm=confusion_matrix(pred1,y_test)
confm

array([[23, 22,  0,  0,  0],
       [15,  9,  0,  0,  0],
       [ 0,  0, 37,  0,  0],
       [ 0,  0,  0, 13, 10],
       [ 0,  0,  0, 10, 19]])